// <auto-generated />
using Core.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Model.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200718085404_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Model.Course", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cid")
                        .HasColumnType("int");

                    b.Property<string>("Cname")
                        .HasColumnName("cname")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<int>("Tid")
                        .HasColumnName("tid")
                        .HasColumnType("int");

                    b.HasKey("Cid")
                        .HasName("PRIMARY");

                    b.ToTable("course");
                });

            modelBuilder.Entity("Core.Model.Sc", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnName("sid")
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnName("cid")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnName("score")
                        .HasColumnType("int");

                    b.HasKey("Sid", "Cid")
                        .HasName("PRIMARY");

                    b.ToTable("sc");
                });

            modelBuilder.Entity("Core.Model.Student", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sid")
                        .HasColumnType("int");

                    b.Property<int>("Sage")
                        .HasColumnName("sage")
                        .HasColumnType("int");

                    b.Property<string>("Sname")
                        .HasColumnName("sname")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Ssex")
                        .HasColumnName("ssex")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.HasKey("Sid")
                        .HasName("PRIMARY");

                    b.ToTable("student");
                });

            modelBuilder.Entity("Core.Model.Teacher", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tid")
                        .HasColumnType("int");

                    b.Property<string>("Tname")
                        .HasColumnName("tname")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.HasKey("Tid")
                        .HasName("PRIMARY");

                    b.ToTable("teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
